# -*- coding: utf-8 -*-
"""Health Management system 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quRK5kjIEiAE_XAzxzmoIH4hfI0meSBa
"""

import datetime

# To add the values
def add():
    name = input('Enter your name: ')
    print('Enter 1 for exercise addition and 2 for food addition: ')
    enter = int(input())

    if enter == 1:
        exercise = input('Enter the name of the exercise: ')
        with open(f"{name}_exercise.txt", 'a') as file:
            file.write('\n' + exercise)
            file.write(f" {datetime.datetime.now()}")
            print('Successfully entered.')
    elif enter == 2:
        food = input('Enter the name of the food: ')
        with open(f"{name}_food.txt", 'a') as file:
            file.write('\n' + food)
            file.write(f" {datetime.datetime.now()}")
            print('Successfully entered.')
    else:
        print('You entered the wrong input value.')

# To review the values
def review():
    try:
        name = input('Enter your name: ')
        print('Enter 1 for exercise addition and 2 for food addition to view: ')
        enter = int(input())

        if enter == 1:
            with open(f"{name}_exercise.txt", 'r') as file:
                reading = file.read()
                print(reading)
        elif enter == 2:
            with open(f"{name}_food.txt", 'r') as file:
                reading = file.read()
                print(reading)
        else:
            print('You entered the wrong input value.')

    except FileNotFoundError:
        print('File does not exist.')

print('This is a Health management system. Enter 1 to add and 2 to check input: ')
valueI = int(input())
if valueI == 1:
    add()
elif valueI == 2:
    review()