# -*- coding: utf-8 -*-
"""rock_paper_scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cROWFKWm06LD-pNd8CQJ8ZwbywEMIhL
"""

import random

def game():
    print('This is rock paper scissor game')
    start = input('start the game press Y to start N to leave')
    if start == 'Y':
        i = 1
        y_count = 0
        c_count = 0
        while i < 10:
            elements = ['rock', 'paper', 'scissor']
            computer = random.choice(elements)
            y_enter = input('enter your input: ')

            if y_enter == 'rock' and computer == 'rock':
                print('Drawn', '\ncomputer choice was', computer)
                y_count += 1
                c_count += 1
                print(10 - i, 'chances left')

            elif y_enter == 'rock' and computer == 'paper':
                print('COMPUTER WON!  ', '\ncomputer choice was', computer)
                c_count += 1
                print(10 - i, 'chances left')
            elif y_enter == 'rock' and computer == 'scissor':
                print('YOU WON!', '\ncomputer choice was', computer)
                y_count += 1
                print(10 - i, 'chances left')

            elif y_enter == 'paper' and computer == 'scissor':
                print('COMPUTER WON! ', '\ncomputer choice was', computer)
                c_count += 1
                print(10 - i, 'chances left')
            elif y_enter == 'paper' and computer == 'rock':
                print('YOU WON! ', '\ncomputer choice was', computer)
                y_count += 1
                print(10 - i, 'chances left')
            elif y_enter == 'paper' and computer == 'paper':
                print('Drawn', '\ncomputer choice was', computer)
                y_count += 1
                c_count += 1
                print(10 - i, 'chances left')

            elif y_enter == 'scissor' and computer == 'rock':
                print('COMPUTER WON!  ', '\ncomputer choice was', computer)
                c_count += 1
                print(10 - i, 'chances left')
            elif y_enter == 'scissor' and computer == 'paper':
                print('YOU WON!', '\ncomputer choice was', computer)
                y_count += 1
                print(10 - i, 'chances left')
            elif y_enter == 'scissor' and computer == 'scissor':
                print('Drawn', '\ncomputer choice was', computer)
                y_count += 1
                c_count += 1
                print(10 - i, 'chances left')
            else:
                print('you entered wrong input')
                break
            i = i + 1
        if y_count > c_count:
            print('You Won the Game')
            print(f"your wins were {y_count} and computer wins was {c_count}")
        elif y_count == c_count:
            print('GAME DRAWN')
        else:
            print('Computer won the Game! ')
            print(f"your wins were {y_count} and computer wins was {c_count}")
    else:
        print('you are outside')

game()
again  = input('you want to play again enter yes to play again ')
if again=='yes':
    print(game())
else:
    print('Thank You for playing !')

